spring:
  datasource:
    url: jdbc:postgresql://localhost:5802/rweather_db_container_db
    driver-class-name: org.postgresql.Driver
    username: user
    password: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true