version: '3.5'

services:
  rest-db:
    image: postgres
    container_name: weather_db_container-db
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=rweather_db_container_db
    ports:
      - "5802:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data